# Generated by Django 3.2.25 on 2024-12-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagecontent',
            old_name='content',
            new_name='html_content',
        ),
    ]
